apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::199970863510:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::199970863510:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-19X3ZKM8B8YA4
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-06-25T18:52:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2189"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: dac0a33e-6e1b-4b96-9554-8cd1b8fe4478
